version: '3'

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      
  backend:
    image: norff/kittygram_backend
    environment:
      - DB_HOST=127.0.0.1
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/collected_static
      - media:/app/media

  frontend:
    image: norff/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/staticfiles

  gateway:
    image: norff/kittygram_gateway
    env_file: .env
    depends_on:
      - frontend
      - backend
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 80:80

volumes:
  pg_data:
  static:
  media:
